//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articulos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Articulos()
        {
            this.DetallesComprobanteArticulos = new HashSet<DetallesComprobanteArticulos>();
            this.IngresoMateriales = new HashSet<IngresoMateriales>();
        }
    
        public int IDArticulo { get; set; }
        public int IDCategoria { get; set; }
        public Nullable<int> IdAlmacen { get; set; }
        public Nullable<int> IdUbicacion { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Codigo { get; set; }
        public Nullable<double> Stock { get; set; }
        public Nullable<double> Iva { get; set; }
    
        public virtual Categorias Categorias { get; set; }
        public virtual Ubicacion Ubicacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallesComprobanteArticulos> DetallesComprobanteArticulos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IngresoMateriales> IngresoMateriales { get; set; }
    }
}
