//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comprobantes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comprobantes()
        {
            this.DetallesPago = new HashSet<DetallesPago>();
            this.DetallesComprobanteArticulos = new HashSet<DetallesComprobanteArticulos>();
        }
    
        public int IdComprobante { get; set; }
        public string Sucursal { get; set; }
        public string NoFactura { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public Nullable<int> IdTipoComprobante { get; set; }
        public Nullable<int> IdCentroCosto { get; set; }
        public Nullable<int> IdTipoFactura { get; set; }
        public Nullable<double> Importe { get; set; }
        public Nullable<int> Contable { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public Nullable<int> IdCondicionCompra { get; set; }
        public Nullable<int> IdEstado { get; set; }
        public Nullable<double> IIBB { get; set; }
        public Nullable<double> Retenciones { get; set; }
        public Nullable<double> ConceptosNograbado { get; set; }
        public Nullable<double> PercepcionIva { get; set; }
        public Nullable<double> ImporteNeto { get; set; }
    
        public virtual CentroCostos CentroCostos { get; set; }
        public virtual CondicionesCompra CondicionesCompra { get; set; }
        public virtual Contable Contable1 { get; set; }
        public virtual Estados Estados { get; set; }
        public virtual TiposComprobante TiposComprobante { get; set; }
        public virtual TiposFactura TiposFactura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallesPago> DetallesPago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallesComprobanteArticulos> DetallesComprobanteArticulos { get; set; }
    }
}
