//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentaCorriente
    {
        public int IdCuentaCorriente { get; set; }
        public Nullable<int> IDProveedor { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Vencimiento { get; set; }
        public string Comentario { get; set; }
    }
}
