//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatosEmpleadosActivos
    {
        public int IDEmpleado { get; set; }
        public string NoLegajo { get; set; }
        public byte[] ImagenPerfil { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string DNI { get; set; }
        public string CUIL { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string Sexo { get; set; }
        public string EstadoCivil { get; set; }
        public string Nacionalidad { get; set; }
        public string Domicilio { get; set; }
        public string Localidades { get; set; }
        public string CodigoPostal { get; set; }
        public string Descripcion { get; set; }
        public string CategoriaEmpleado1 { get; set; }
        public Nullable<bool> Activo { get; set; }
    }
}
