//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallesPago
    {
        public int IdDetallePago { get; set; }
        public Nullable<int> idComprobante { get; set; }
        public Nullable<int> IdPago { get; set; }
    
        public virtual Comprobantes Comprobantes { get; set; }
        public virtual Pagos Pagos { get; set; }
    }
}
