//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleMediosPagos
    {
        public int IdDetalleMedioPago { get; set; }
        public Nullable<int> IdMedioPago { get; set; }
        public string NoCheque { get; set; }
        public Nullable<System.DateTime> FechaVencimientoCheque { get; set; }
        public Nullable<int> IdBanco { get; set; }
        public Nullable<double> Importe { get; set; }
        public Nullable<int> IdPago { get; set; }
    
        public virtual Bancos Bancos { get; set; }
        public virtual MediosPago MediosPago { get; set; }
        public virtual Pagos Pagos { get; set; }
    }
}
