//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallePago
    {
        public string Sucursal { get; set; }
        public string NoFactura { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public int Idpago { get; set; }
        public Nullable<System.DateTime> Expr1 { get; set; }
        public Nullable<double> Importe { get; set; }
        public string Concepto { get; set; }
        public string MediosPago { get; set; }
        public string NoCheque { get; set; }
        public Nullable<System.DateTime> FechaVencimientoCheque { get; set; }
        public Nullable<double> Expr2 { get; set; }
    }
}
