//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleProveedor_ProductorSeguro
    {
        public int IdDetalleProveedor_ProductorSeguro { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public Nullable<int> IdProductorSeguro { get; set; }
    
        public virtual ProductoresSeguro ProductoresSeguro { get; set; }
        public virtual Proveedores Proveedores { get; set; }
    }
}
