//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleMediosPagos
    {
        public int IdDetalleMedioPago { get; set; }
        public Nullable<int> IdMedioPago { get; set; }
        public string NoCheque { get; set; }
        public Nullable<System.DateTime> FechaVencimientoCheque { get; set; }
        public Nullable<int> IdBanco { get; set; }
        public Nullable<double> Importe { get; set; }
        public Nullable<int> IdPago { get; set; }
    
        public virtual Bancos Bancos { get; set; }
        public virtual MediosPago MediosPago { get; set; }
        public virtual Pagos Pagos { get; set; }
    }
}
