//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallesComprobanteArticulos
    {
        public int idTable_DetallesComprobanteArticulos { get; set; }
        public Nullable<int> IdComprobante { get; set; }
        public Nullable<int> IdArticulo { get; set; }
        public Nullable<double> Cantidad { get; set; }
        public Nullable<double> Precio { get; set; }
        public Nullable<double> Iva { get; set; }
        public Nullable<double> Importe { get; set; }
        public Nullable<double> IvaCalculado { get; set; }
    
        public virtual Articulos Articulos { get; set; }
        public virtual Comprobantes Comprobantes { get; set; }
    }
}
