//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallesSolicitudesEmpleo
    {
        public Nullable<System.DateTime> Fecha { get; set; }
        public int IdPersona { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Sexo { get; set; }
        public string DNI { get; set; }
        public string CUIL { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string Nacionalidad { get; set; }
        public string Domicilio { get; set; }
        public string localidad { get; set; }
        public string CodigoPostal { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public string EstadoCivil { get; set; }
        public Nullable<int> Hijos { get; set; }
        public Nullable<bool> RegistroConducir { get; set; }
        public string Obrasocial { get; set; }
        public Nullable<bool> LibretaFondoDesempleo { get; set; }
        public string AntecedentesLaborales { get; set; }
        public Nullable<double> PretencionRemunerativa { get; set; }
    }
}
