//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleProveedor_ProductorSeguro
    {
        public int IdDetalleProveedor_ProductorSeguro { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public Nullable<int> IdProductorSeguro { get; set; }
    
        public virtual ProductoresSeguro ProductoresSeguro { get; set; }
        public virtual Proveedores Proveedores { get; set; }
    }
}
