//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleados()
        {
            this.AfectadoEmpresaCliente = new HashSet<AfectadoEmpresaCliente>();
            this.Vehiculos = new HashSet<Vehiculos>();
        }
    
        public int IDEmpleado { get; set; }
        public Nullable<int> Orden { get; set; }
        public byte[] ImagenPerfil { get; set; }
        public Nullable<bool> Activo { get; set; }
        public int NoLegajo { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string DNI { get; set; }
        public string CUIL { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public string Domicilio { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<int> Hijos { get; set; }
        public Nullable<int> idDepartamento { get; set; }
        public Nullable<int> IdObraSocial { get; set; }
        public Nullable<int> idSindicato { get; set; }
        public Nullable<int> idEspecialidad { get; set; }
        public Nullable<int> idCategoriaEmpleado { get; set; }
        public string NoCuentaFondoDesempleo { get; set; }
        public Nullable<bool> Ieric { get; set; }
        public Nullable<System.DateTime> FechaCeseLaboral { get; set; }
        public string Comentario { get; set; }
        public Nullable<int> IdLocalidad { get; set; }
        public Nullable<int> EstadoCivil { get; set; }
        public Nullable<int> IdNacionalidad { get; set; }
        public Nullable<bool> LibretaFondoDesempleo { get; set; }
        public Nullable<int> IdSexo { get; set; }
        public Nullable<bool> RegistroConducir { get; set; }
        public Nullable<int> IDEmpresaAFectada { get; set; }
        public Nullable<int> IDZona { get; set; }
        public Nullable<int> IdUsuarioAlta { get; set; }
        public Nullable<int> IdUsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<System.DateTime> FechaUltimaModificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AfectadoEmpresaCliente> AfectadoEmpresaCliente { get; set; }
        public virtual CategoriaEmpleado CategoriaEmpleado { get; set; }
        public virtual Departamentos Departamentos { get; set; }
        public virtual EmpresasClientes EmpresasClientes { get; set; }
        public virtual EstadoCivil EstadoCivil1 { get; set; }
        public virtual Localidades Localidades { get; set; }
        public virtual Nacionalidades Nacionalidades { get; set; }
        public virtual ObraSocial ObraSocial { get; set; }
        public virtual Sexos Sexos { get; set; }
        public virtual Zonas Zonas { get; set; }
        public virtual Especialidades Especialidades { get; set; }
        public virtual Sindicatos Sindicatos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vehiculos> Vehiculos { get; set; }
    }
}
