//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresas
    {
        public int idEmpresa { get; set; }
        public string Nombre { get; set; }
        public string Razon { get; set; }
        public string CUIT { get; set; }
        public string Direccion { get; set; }
        public Nullable<int> idProvincia { get; set; }
        public Nullable<int> IdLocalidad { get; set; }
        public string CodigoPostal { get; set; }
    }
}
