//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngresoMateriales
    {
        public int iDingresoMateriales { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string NoRemito { get; set; }
        public Nullable<int> IdAlmacen { get; set; }
        public Nullable<int> IdRecepcion { get; set; }
        public Nullable<int> idArticulo { get; set; }
        public Nullable<double> Cantidad { get; set; }
    
        public virtual Almacenes Almacenes { get; set; }
        public virtual Articulos Articulos { get; set; }
    }
}
