//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngresoMateriales
    {
        public int iDingresoMateriales { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string NoRemito { get; set; }
        public Nullable<int> IdAlmacen { get; set; }
        public Nullable<int> IdRecepcion { get; set; }
        public Nullable<int> idArticulo { get; set; }
        public Nullable<double> Cantidad { get; set; }
    
        public virtual Almacenes Almacenes { get; set; }
        public virtual Articulos Articulos { get; set; }
    }
}
