//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListaTalleresMecanicos
    {
        public int IDTalleres { get; set; }
        public string NombreTaller { get; set; }
        public string Direccion { get; set; }
        public string Localidades { get; set; }
        public string DescripcionTaller { get; set; }
        public string NombreEncargado { get; set; }
        public string TelefonoCotacto { get; set; }
    }
}
