//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mantenimiento
    {
        public int IDMantenimiento { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> IdVehiculo { get; set; }
        public Nullable<int> Km { get; set; }
        public Nullable<int> IDEmpleado { get; set; }
        public Nullable<int> IDTaller { get; set; }
        public Nullable<int> IDActividadMantenimiento { get; set; }
        public string Comentario { get; set; }
        public Nullable<int> IDUserTransac { get; set; }
    
        public virtual ActividadMantenimiento ActividadMantenimiento { get; set; }
    }
}
