//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mantenimiento
    {
        public int IDMantenimiento { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> IdVehiculo { get; set; }
        public Nullable<int> Km { get; set; }
        public Nullable<int> IDEmpleado { get; set; }
        public Nullable<int> IDTaller { get; set; }
        public Nullable<int> IDActividadMantenimiento { get; set; }
        public string Comentario { get; set; }
        public Nullable<int> IDUserTransac { get; set; }
    
        public virtual ActividadMantenimiento ActividadMantenimiento { get; set; }
        public virtual Empleados Empleados { get; set; }
        public virtual Talleres Talleres { get; set; }
        public virtual Vehiculos Vehiculos { get; set; }
    }
}
