//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class PadronRgsRet
    {
        public int ID { get; set; }
        public string Regimen { get; set; }
        public System.DateTime FechaPublicacion { get; set; }
        public System.DateTime FechaDesde { get; set; }
        public System.DateTime FechaHasta { get; set; }
        public string Cuit { get; set; }
        public string TipoContribuyenteInsc { get; set; }
        public string MarcaAltaBaja { get; set; }
        public string MarcaCambioAlicuota { get; set; }
        public double Alicuota { get; set; }
        public int Grupo { get; set; }
    }
}
