//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personas()
        {
            this.Referencias = new HashSet<Referencias>();
            this.SolicitudesEmpleo = new HashSet<SolicitudesEmpleo>();
        }
    
        public int IdPersona { get; set; }
        public byte[] ImagenPerfil { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string DNI { get; set; }
        public string CUIL { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public string Domicilio { get; set; }
        public Nullable<int> IdLocalidad { get; set; }
        public Nullable<int> idObraSocial { get; set; }
        public Nullable<int> Hijos { get; set; }
        public Nullable<int> EstadoCivil { get; set; }
        public Nullable<int> IdNacionalidad { get; set; }
        public Nullable<bool> LibretaFondoDesempleo { get; set; }
        public Nullable<int> IdSexo { get; set; }
        public Nullable<bool> RegistroConducir { get; set; }
    
        public virtual EstadoCivil EstadoCivil1 { get; set; }
        public virtual Localidades Localidades { get; set; }
        public virtual Nacionalidades Nacionalidades { get; set; }
        public virtual ObraSocial ObraSocial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Referencias> Referencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolicitudesEmpleo> SolicitudesEmpleo { get; set; }
    }
}
