//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proveedores()
        {
            this.Comprobantes = new HashSet<Comprobantes>();
            this.CuentaCorriente = new HashSet<CuentaCorriente>();
            this.DetalleProveedor_ProductorSeguro = new HashSet<DetalleProveedor_ProductorSeguro>();
            this.PolizasSeguro = new HashSet<PolizasSeguro>();
        }
    
        public int IdProveedores { get; set; }
        public string Nombre { get; set; }
        public string Razon { get; set; }
        public string Cuit { get; set; }
        public string IngresosBrutos { get; set; }
        public string Direccion { get; set; }
        public int IDProvincia { get; set; }
        public int IDLocalidad { get; set; }
        public string Telefono { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<int> IDRubro { get; set; }
        public Nullable<int> UserAltaID { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<int> UserUltModificacion { get; set; }
        public Nullable<System.DateTime> FechaUltimaModificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comprobantes> Comprobantes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuentaCorriente> CuentaCorriente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleProveedor_ProductorSeguro> DetalleProveedor_ProductorSeguro { get; set; }
        public virtual Localidades Localidades { get; set; }
        public virtual NetUser NetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PolizasSeguro> PolizasSeguro { get; set; }
        public virtual Provincias Provincias { get; set; }
        public virtual Proveedores Proveedores1 { get; set; }
        public virtual Proveedores Proveedores2 { get; set; }
        public virtual RubroProveedor RubroProveedor { get; set; }
    }
}
