//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proveedores()
        {
            this.DetalleProveedor_ProductorSeguro = new HashSet<DetalleProveedor_ProductorSeguro>();
        }
    
        public int IdProveedores { get; set; }
        public string Nombre { get; set; }
        public string Razon { get; set; }
        public string Cuit { get; set; }
        public string IngresosBrutos { get; set; }
        public string Direccion { get; set; }
        public int IDProvincia { get; set; }
        public int IDLocalidad { get; set; }
        public string Telefono { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<int> IDRubro { get; set; }
        public Nullable<int> UserAltaID { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<int> UserUltModificacion { get; set; }
        public Nullable<System.DateTime> FechaUltimaModificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleProveedor_ProductorSeguro> DetalleProveedor_ProductorSeguro { get; set; }
        public virtual Localidades Localidades { get; set; }
        public virtual NetUser NetUser { get; set; }
        public virtual Proveedores Proveedores1 { get; set; }
        public virtual Proveedores Proveedores2 { get; set; }
        public virtual RubroProveedor RubroProveedor { get; set; }
        public virtual Provincias Provincias { get; set; }
    }
}
