//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudesEmpleo
    {
        public int IdSolicitudEmpleo { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> idPersona { get; set; }
        public string AntecedentesLaborales { get; set; }
        public Nullable<double> PretencionRemunerativa { get; set; }
    
        public virtual Personas Personas { get; set; }
    }
}
