//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudesEmpleo
    {
        public int IdSolicitudEmpleo { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> idPersona { get; set; }
        public string AntecedentesLaborales { get; set; }
        public Nullable<double> PretencionRemunerativa { get; set; }
    
        public virtual Personas Personas { get; set; }
    }
}
