//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubMenus
    {
        public int Id { get; set; }
        public string Submenu { get; set; }
        public Nullable<int> MenuID { get; set; }
        public Nullable<bool> IsEnable { get; set; }
    
        public virtual Menus Menus { get; set; }
    }
}
