//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Talleres
    {
        public int IDTalleres { get; set; }
        public string NombreTaller { get; set; }
        public string Direccion { get; set; }
        public Nullable<int> IDLocalidad { get; set; }
        public string TelefonoCotacto { get; set; }
        public string NombreEncargado { get; set; }
        public Nullable<int> IdTipoTaller { get; set; }
    
        public virtual Localidades Localidades { get; set; }
        public virtual TipoTaller TipoTaller { get; set; }
    }
}
