//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public string IDUser { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<int> IDProfile { get; set; }
        public byte[] PasswordHash { get; set; }
    
        public virtual Profiles Profiles { get; set; }
    }
}
