//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Proveedores
    {
        public string Nombre { get; set; }
        public string Razon { get; set; }
        public string Cuit { get; set; }
        public string IngresosBrutos { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public string Localidades { get; set; }
        public string Provincias { get; set; }
        public string RubroProveedor { get; set; }
    }
}
