//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_DetalleArticuloComprobante
    {
        public string Nombre { get; set; }
        public Nullable<double> Cantidad { get; set; }
        public Nullable<double> Precio { get; set; }
        public Nullable<double> Importe { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public int IdComprobante { get; set; }
        public int idTable_DetallesComprobanteArticulos { get; set; }
        public Nullable<double> Iva { get; set; }
    }
}
