//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AfectadoEmpresaCliente
    {
        public int IDAfectadoEmpresaCliente { get; set; }
        public Nullable<int> IdEmpresaCliente { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
    
        public virtual Empleados Empleados { get; set; }
        public virtual EmpresasClientes EmpresasClientes { get; set; }
    }
}
