//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Almacenes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Almacenes()
        {
            this.IngresoMateriales = new HashSet<IngresoMateriales>();
        }
    
        public int IdAlmacen { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public string Nombre { get; set; }
        public string Codigo { get; set; }
        public Nullable<int> IdEncargado { get; set; }
        public Nullable<int> IDZona { get; set; }
    
        public virtual Zonas Zonas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IngresoMateriales> IngresoMateriales { get; set; }
    }
}
