//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallesPago
    {
        public int IdDetallePago { get; set; }
        public Nullable<int> idComprobante { get; set; }
        public Nullable<int> IdPago { get; set; }
    
        public virtual Comprobantes Comprobantes { get; set; }
        public virtual Pagos Pagos { get; set; }
    }
}
