//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallePago
    {
        public string Sucursal { get; set; }
        public string NoFactura { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public int Idpago { get; set; }
        public Nullable<System.DateTime> Expr1 { get; set; }
        public Nullable<double> Importe { get; set; }
        public string Concepto { get; set; }
        public string MediosPago { get; set; }
        public string NoCheque { get; set; }
        public Nullable<System.DateTime> FechaVencimientoCheque { get; set; }
        public Nullable<double> Expr2 { get; set; }
    }
}
