//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresas
    {
        public int idEmpresa { get; set; }
        public string Nombre { get; set; }
        public string Razon { get; set; }
        public string CUIT { get; set; }
        public string Direccion { get; set; }
        public Nullable<int> idProvincia { get; set; }
        public Nullable<int> IdLocalidad { get; set; }
        public string CodigoPostal { get; set; }
    }
}
